name: GKE Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true


    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    
    
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker 
        docker build -t gcr.io/corded-evening-434319-k3/time-api:$GITHUB_SHA .
        docker push  gcr.io/corded-evening-434319-k3/time-api:$GITHUB_SHA
      
    # - name: Authenticate Docker
    #   run: gcloud auth configure-docker

    # - name: Build the Docker image
    #   run: docker build -t gcr.io/corded-evening-434319-k3/time-api:$GITHUB_SHA .

  
    # - name: Configure Docker Client
    #   run:  |-
    #     gcloud auth configure-docker --quiet

    # - name: Push the Docker image to GCR
    #   run: docker push gcr.io/corded-evening-434319-k3/time-api:$GITHUB_SHA

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/time-api time-api=gcr.io/corded-evening-434319-k3/time-api:$GITHUB_SHA
